### ISSUE TITLE
PMSmart Export fails

### ISSUE THREAD

**Issue by ckunki** [itsallcode/white-rabbit#151]
Error message: Expected day 2021-05-17 selected

[2021-05.json.txt](https://github.com/itsallcode/white-rabbit/files/6514204/2021-05.json.txt)

**Comment by ckunki** [comment]
`2021-05-20 10:33:43,736 ERROR o.i.w.j.u.ProjectReportViewer [pool-3-thread-1] ERROR org.itsallcode.whiterabbit.jfxui.ui.ProjectReportViewer - Error exporting project report
java.lang.IllegalStateException: Expected day 2021-05-17 selected
	at org.itsallcode.whiterabbit.plugin.pmsmart.web.page.WeekViewPage.selectWeek(WeekViewPage.java:48) ~[pmsmart-plugin.jar:?]
	at org.itsallcode.whiterabbit.plugin.pmsmart.PMSmartExporter.export(PMSmartExporter.java:55) ~[pmsmart-plugin.jar:?]
	at org.itsallcode.whiterabbit.jfxui.ui.ProjectReportViewer.lambda$exportReport$3(ProjectReportViewer.java:77) ~[white-rabbit-fx-1.6.0-SNAPSHOT.jar:?]
	at org.itsallcode.whiterabbit.logic.service.scheduling.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:23) [white-rabbit-fx-1.6.0-SNAPSHOT.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
	at java.lang.Thread.run(Thread.java:830) [?:?]`

**Comment by p1pp5l3r** [comment]
+1: Same on my notebook

**Comment by kaklakariada** [comment]
Could happen when a holiday is on Monday to Friday.
This is already fixed in #133.
Please try with the latest version from develop.

**Comment by ckunki** [comment]
I'm sorry - behavior is unchanged, even with latest develop.

**Comment by kaklakariada** [comment]
Please try to fix this and create a pull request. I don't have time right now.

**Comment by ckunki** [comment]
Problem was `DateSelector` being too unspecific.

BEFORE FIX: DateSelector excluded days in calendar month view that belonged to **preceding or following month** (class='dxeCalendarOtherMonth_PlasticBlue').

AFTER FIX: DateSelector additionally excludes **week numbers** (class='dxeCalendarWeekNumber_PlasticBlue').

This problem probably resulted in an ambigue selection only if a specific number _n_ was displayed twice in calendar month view: 
- once with _n_ being the number of a day in current month and 
- second with _n_ being the number of a calendar week contained in current month

**Comment by ckunki** [comment]
See PR https://github.com/itsallcode/white-rabbit/pull/159

**Comment by ckunki** [comment]
Hm. 
Sonar rejects the changes due to 6 uncovered lines on new code.
I feel innocent as I did not create this class in the first place. 
Additionally the [uncovered lines](https://sonarcloud.io/component_measures?id=org.itsallcode.whiterabbit%3Awhite-rabbit&metric=new_uncovered_lines&pullRequest=159&selected=org.itsallcode.whiterabbit%3Awhite-rabbit%3Aplugins%2Fpmsmart%2Fsrc%2Fmain%2Fjava%2Forg%2Fitsallcode%2Fwhiterabbit%2Fplugin%2Fpmsmart%2Fweb%2Fpage%2FDateSelector.java&view=list) are hard or impossible to test and I don't see significant benefit in testing these lines.

Is there any workaround?

**Comment by kaklakariada** [comment]
Thank you very much for investigation and finding a fix!

As we don't have integration tests for the exporter, there can't be test coverage. We can still merge, even if sonar complains.

**Comment by ckunki** [comment]
Thanks very much!
I first want to make another improvement in order to reduce size of ConfigMock and to narrow interfaces of class Config.
