### ISSUE TITLE
UI becomes unresponsive after switching monitors

### ISSUE THREAD

**Issue by kaklakariada** [itsallcode/white-rabbit#211]
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at com.sun.prism.d3d.D3DPipeline.getD3DResourceFactory(D3DPipeline.java:217)
        at com.sun.prism.d3d.D3DPipeline.getResourceFactory(D3DPipeline.java:284)
        at com.sun.scenario.effect.impl.prism.ps.PPSRenderer.validate(PPSRenderer.java:101)
        at com.sun.scenario.effect.impl.prism.ps.PPSRenderer.getCompatibleImage(PPSRenderer.java:221)
        at com.sun.scenario.effect.impl.prism.ps.PPSRenderer.getCompatibleImage(PPSRenderer.java:67)
        at com.sun.scenario.effect.Effect.getCompatibleImage(Effect.java:479)
        at com.sun.javafx.sg.prism.NodeEffectInput.getImageDataForBoundedNode(NodeEffectInput.java:228)
        at com.sun.javafx.sg.prism.NodeEffectInput.filter(NodeEffectInput.java:131)
        at com.sun.scenario.effect.FilterEffect.filter(FilterEffect.java:185)
        at com.sun.scenario.effect.Offset.filter(Offset.java:160)
        at com.sun.scenario.effect.Merge.filter(Merge.java:148)
        at com.sun.scenario.effect.DelegateEffect.filter(DelegateEffect.java:70)
        at com.sun.scenario.effect.impl.prism.PrEffectHelper.render(PrEffectHelper.java:166)
        at com.sun.javafx.sg.prism.EffectFilter.render(EffectFilter.java:61)
        at com.sun.javafx.sg.prism.NGNode.renderEffect(NGNode.java:2384)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2069)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
        at com.sun.javafx.sg.prism.NGNode.renderForClip(NGNode.java:2313)
        at com.sun.javafx.sg.prism.NGNode.renderRectClip(NGNode.java:2207)
        at com.sun.javafx.sg.prism.NGNode.renderClip(NGNode.java:2233)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2066)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at com.sun.javafx.sg.prism.NGGroup.renderContent(NGGroup.java:270)
        at com.sun.javafx.sg.prism.NGRegion.renderContent(NGRegion.java:579)
        at com.sun.javafx.sg.prism.NGNode.doRender(NGNode.java:2072)
        at com.sun.javafx.sg.prism.NGNode.render(NGNode.java:1964)
        at com.sun.javafx.tk.quantum.ViewPainter.doPaint(ViewPainter.java:480)
        at com.sun.javafx.tk.quantum.ViewPainter.paintImpl(ViewPainter.java:329)
        at com.sun.javafx.tk.quantum.PresentingPainter.run(PresentingPainter.java:92)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at com.sun.javafx.tk.RenderJob.run(RenderJob.java:58)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:126)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by kaklakariada** [comment]
Not reproducible, only occurred once.
