### ISSUE TITLE
Error using WebStart with plugins

### ISSUE THREAD

**Issue by kaklakariada** [itsallcode/white-rabbit#77]
Loading local plugins from `$HOME/.whiterabbit/plugins/` is not supported when starting WhiteRabbit via WebStart.

Workaround: delete local plugins: `rm -i $HOME/.whiterabbit/plugins/*.jar`

**Comment by kaklakariada** [comment]
```
net.sourceforge.jnlp.LaunchException: Fatal: Launch Error: Could not launch JNLP file. The application has not been initialized, for more information execute javaws/browser from the command line and send a bug report.
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:408)
	at net.sourceforge.jnlp.Launcher.access$200(Launcher.java:70)
	at net.sourceforge.jnlp.Launcher$TgThread.run(Launcher.java:654)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at net.sourceforge.jnlp.Launcher.launchApplication(Launcher.java:401)
	... 2 more
Caused by: java.lang.RuntimeException: Exception in Application init method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:898)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:198)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.ServiceConfigurationError: org.itsallcode.whiterabbit.api.Plugin: Provider org.itsallcode.whiterabbit.plugin.csv.CSVExporterPlugin could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at org.itsallcode.whiterabbit.logic.service.plugin.PluginRegistry.loadPlugin(PluginRegistry.java:111)
	at org.itsallcode.whiterabbit.logic.service.plugin.PluginRegistry.lambda$loadPlugins$1(PluginRegistry.java:83)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ServiceLoader$ProviderSpliterator.tryAdvance(ServiceLoader.java:1491)
	at java.base/java.util.Spliterator.forEachRemaining(Spliterator.java:326)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.itsallcode.whiterabbit.logic.service.plugin.PluginRegistry.loadPlugins(PluginRegistry.java:49)
	at org.itsallcode.whiterabbit.logic.service.plugin.PluginRegistry.load(PluginRegistry.java:43)
	at org.itsallcode.whiterabbit.logic.service.plugin.PluginManager.create(PluginManager.java:27)
	at org.itsallcode.whiterabbit.logic.service.AppService.create(AppService.java:100)
	at org.itsallcode.whiterabbit.jfxui.JavaFxApp.doInitialize(JavaFxApp.java:96)
	at org.itsallcode.whiterabbit.jfxui.JavaFxApp.init(JavaFxApp.java:79)
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:827)
	... 2 more
Caused by: java.lang.NullPointerException: Code source security was null
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getPermissions(JNLPClassLoader.java:1086)
	at net.sourceforge.jnlp.runtime.JNLPPolicy.getPermissions(JNLPPolicy.java:119)
	at net.sourceforge.jnlp.runtime.JNLPPolicy.implies(JNLPPolicy.java:252)
	at java.base/java.security.ProtectionDomain.implies(ProtectionDomain.java:321)
	at java.base/java.security.ProtectionDomain.impliesWithAltFilePerm(ProtectionDomain.java:353)
	at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:450)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.getAccessControlContextForClassLoading(JNLPClassLoader.java:2085)
	at net.sourceforge.jnlp.runtime.classloader.JNLPClassLoader.findClass(JNLPClassLoader.java:1592)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:575)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at PluginClassLoader-csv-plugin-signed.jar//org.itsallcode.whiterabbit.plugin.csv.CSVExporterPlugin.<init>(CSVExporterPlugin.java:10)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.ServiceLoader$ProviderImpl$2.run(ServiceLoader.java:787)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:792)
	... 32 more
```

**Comment by kaklakariada** [comment]
Webstart is not supported any more
